### ISSUE TITLE
is website ok ?

### ISSUE THREAD

**Issue by flutter-painter** [aptabase/aptabase_flutter#11]
Hi,

I get a weird error when logging on my aptabase account,
Also website is strangely displayed at : https://aptabase.com/

Sorry for opening up an issue but seemed the easiest

**Comment by GabrielRozendo** [comment]
As this repo is related to flutter, I'd recommend you @flutter-painter open that issue on respectively repo: https://github.com/aptabase/aptabase-com

also, the website looks ok for me tho (Safari, Mac, only landing page)

**Comment by flutter-painter** [comment]
Thank you for the heads up, Indeed all good in chrome
