### ISSUE TITLE
Flutter lifecycle management broken

### ISSUE THREAD

**Issue by lora-explora** [aptabase/aptabase_flutter#15]
I found a bug regarding lifecycle management. 

In my Flutter app, I use a lifecycle observer to perform some operations when the app enters the foreground.
This can be done using AppLifecycleListener or by extending WidgetsBindingObserver and overriding didChangeAppLifecycleState().

Aptabase blocks the lifecycle events though, so the callbacks are not getting called anymore.

This may also cause an issue with device language switching.

**Comment by lora-explora** [comment]
I see you already have a PR open for this 🙏 When do you plan on including it? I want to release my app very soon and want to use tracking & need the onresume logic at the same time.

**Comment by cristipufu** [comment]
@lora-explora do you wish to review the PR before merging it and releasing a new version? https://github.com/aptabase/aptabase_flutter/pull/16

**Comment by cristipufu** [comment]
@lora-explora we just released 0.4.1. Let me know if everything works as expected please, thank you!
