### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by flutter-painter** [aptabase/aptabase_flutter#2]
How does the SDK deal with offline devices ?
Does it check if the device is offline before sending events ?
Does it store them until a steady connexion is available ?

**Comment by flutter-painter** [comment]
Good news !
Out of curiosity from a humble Dart writer dealing with users allergic to connectivity ;
Will the SDK check device connectivity before attempting to send data ?
Coming from flutter I assumed implementation would be specific for each OS..

**Comment by goenning** [comment]
Our SDK doesn't explicitly check for that, not sure about the underlying OS though.

Why do you say they allergic to connectivity? Form my experience if you go offline there are very few apps that actually work, in most cases people will have constant internet connection.

**Comment by flutter-painter** [comment]
Thank you for your quick reply !
That's what I thought. I would be curious to mesure how this affects performances. It could make the case for a dedicated Dart/Flutter SDK suited to the needs of the unconstantly connected, i.e. sober sync design.

I beg to disagree and reckon that most people have inconstant connectivity, mostly because of low income vs prepaid internet cost + lack of infrastructure and rural isolation.

To keep this in mind facebook delibarately slowed their employees productivity :

https://www.theverge.com/2015/10/28/9625062/facebook-2g-tuesdays-slow-internet-developing-world

But yeah most people targetted by a paying/add-based app can afford connectivity


________________________________

**Comment by goenning** [comment]
You're right, my comment was based on my own bubble, which is not very representative!

Would you like to contribute with Offline support for the Flutter SDK?

**Comment by flutter-painter** [comment]
Sure ! It would be useful to write connectivity tests,
Will do it slowly, by the end of the summer

**Comment by goenning** [comment]
Awesome, great to have you onboard. There's no rush at all as I still need to work on the batch event ingestion api.

It'll probably be something like:
```
POST /api/v0/events (instead of /api/v0/event for a single event)
[
 { event1 },
 { event2 }
]
``` 

And with regards to the SDK, I was thinking of when trackEvent is called, it would simply enqueue it in memory and then dispatch the list of in-memory events every X seconds if there's internet connectivity

**Comment by rafagazani** [comment]
What are you thinking for offline persistence? sqlite3? file?

**Comment by flutter-painter** [comment]
SEMBAST, there is already a PR : https://github.com/aptabase/aptabase_flutter/pull/6
You could also plug SQLite3 or any kind of db on it, it is modular.
But we left it at that because goenning asked additional rework which required a lot of redesign,
You could fork from the PR if needed though, it works for me in production smoothly

**Comment by cristipufu** [comment]
Hi @rafagazani, @flutter-painter, we merged https://github.com/aptabase/aptabase_flutter/pull/8 and release version 0.4.0. Give it a try and let us know how it goes 😸
