### ISSUE TITLE
Android: Logging seems to fail when testing with actual APKs

### ISSUE THREAD

**Issue by JosipDomazetDev** [aptabase/aptabase_flutter#7]
Hey, 

I  want to disclose that I am not entirely confident if this issue is related to my code or this plugin.

However, when testing with actual APKs (signed & unsigned) I have noticed that no events are actually being sent. When running the same app on the debugger everything works fine (in debug mode). When trying the release version on the debugger nothing is being sent again.

Note that I do have the `INTERNET` permission in place. Now that I am testing with APKs actual debugging is really hard to achieve but my flutter log also seems to be empty. Furthermore, general Internet connectivity is given and Firebase Crashlytics reporting does work without problems in the same app.
I would greatly appreciate it if someone can have a look into this matter. 

Tested device: `Xiaomi X3 Pro`

**Comment by goenning** [comment]
The only thing that comes to mind is the build mode in the Aptabase dashboard. Have you tried switching from Debug to Release?

**Comment by JosipDomazetDev** [comment]
You are correct sir, I did not switch from Debug to Release mode in the dashboard. Everything works as expected. Merry Christmas!
